# Generated by Django 4.1 on 2026-08-07 07:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books_service", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="Cover",
            new_name="cover",
        ),
        migrations.RemoveField(
            model_name="book",
            name="Daily_fee",
        ),
        migrations.AddField(
            model_name="book",
            name="daily_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=10,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
            preserve_default=False,
        ),
    ]
