# Generated by Django 5.2.8 on 2026-08-08 09:39

from datetime import timedelta

from django.conf import settings
from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        (
            "books_service",
            "0002_rename_cover_book_cover_remove_book_daily_fee_and_more",
        ),
        ("borrowing_service", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    def normalize_invalid_borrowing_dates(apps, schema_editor):
        Borrowing = apps.get_model("borrowing_service", "Borrowing")
        invalid_borrowings = Borrowing.objects.filter(
            Q(expected_return_date__lte=models.F("borrow_date"))
            | Q(actual_return_date__lt=models.F("borrow_date"))
        )

        for borrowing in invalid_borrowings.iterator():
            update_fields = []

            if borrowing.expected_return_date <= borrowing.borrow_date:
                borrowing.expected_return_date = borrowing.borrow_date + timedelta(
                    days=1
                )
                update_fields.append("expected_return_date")

            if (
                borrowing.actual_return_date is not None
                and borrowing.actual_return_date < borrowing.borrow_date
            ):
                borrowing.actual_return_date = None
                update_fields.append("actual_return_date")

            if update_fields:
                borrowing.save(update_fields=update_fields)

    operations = [
        migrations.RunPython(
            normalize_invalid_borrowing_dates,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name="borrowing",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("expected_return_date__gt", models.F("borrow_date"))
                ),
                name="expected_return_after_borrow_date",
            ),
        ),
        migrations.AddConstraint(
            model_name="borrowing",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("actual_return_date__isnull", True),
                    ("actual_return_date__gte", models.F("borrow_date")),
                    _connector="OR",
                ),
                name="actual_return_on_or_after_borrow_date",
            ),
        ),
    ]
